name: dear_deer_demo
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.2.2

  cupertino_icons: ^1.0.6
  logger: ^2.5.0
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  get: ^4.7.2

  modal_bottom_sheet: ^3.0.0
  table_calendar: ^3.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/images/

  fonts:
      - family: KakaoSmallSansBold
        fonts:
          - asset: assets/fonts/KakaoSmallSans-Bold.ttf

      - family: KakaoSmallSansRegular
        fonts:
          - asset: assets/fonts/KakaoSmallSans-Regular.ttf

      - family: KakaoSmallSansLight
        fonts:
          - asset: assets/fonts/KakaoSmallSans-Light.ttf

      - family: KakaoBigSansBold
        fonts:
          - asset: assets/fonts/KakaoBigSans-Bold.ttf

      - family: KakaoBigSansExtraBold
        fonts:
          - asset: assets/fonts/KakaoBigSans-ExtraBold.ttf

      - family: KakaoBigSansRegular
        fonts:
          - asset: assets/fonts/KakaoBigSans-Regular.ttf

      - family: LeeSeoyun
        fonts:
          - asset: assets/fonts/LeeSeoyun.ttf

      - family: TJJoyofSinging
        fonts:
          - asset: assets/fonts/TJJoyofSinging.ttf

      - family: KCCGanpan
        fonts:
          - asset: assets/fonts/KCC-Ganpan.ttf